teleop:
  drive:
    type: topic
    message_type: ctrl_pkg/ServoCtrlMsg
    topic_name: /manual_drive
    deadman_buttons: [2]
    axis_mappings:
      - axis: 1
        target: throttle
        scale: 1.0
      - axis: 4
        target: angle
        scale: 1.0
 
